# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 38e3d6aa21c687e8bbf8a5f77a7d8c27e210063319f93e04608fb902a808861d852c2f8900bd8ac296d78a0e4e84ca556d44e54883bb38007cf72dfb57b3293a

test:
  secret_key_base: df727cccf2e6acc810f998042f154e6e26a3821e89cf6b0f32d9483fd75f45ccbdd122f267406021986f9ade1a2d14be98512a138f2768a79ea96859aedce7c0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
